export const modules = [
  {
    id: "ml-basics",
    number: 1,
    title: "What is Machine Learning?",
    shortTitle: "ML basics",
    theme: "teal",
    summary:
      "Machine learning is how software finds patterns from examples instead of following hand-written rules for every case.",
    visual: "A model watches examples, notices patterns, and turns them into predictions.",
    demo: "ml",
    controlLabel: "Dataset noise",
    controlMin: 0,
    controlMax: 100,
    controlStep: 5,
    controlDefault: 20,
    quiz: {
      question: "What makes machine learning different from normal rule-based code?",
      options: [
        "It learns useful patterns from examples",
        "It never makes mistakes",
        "It only works with text",
      ],
      answer: 0,
    },
    takeaway:
      "ML is pattern-finding at scale: examples go in, useful predictions come out.",
    deeper:
      "A model is a function with adjustable parameters. Training changes those parameters until the model's outputs match the examples better.",
  },
  {
    id: "training-inference",
    number: 2,
    title: "Training vs Inference",
    shortTitle: "Train vs use",
    theme: "amber",
    summary:
      "Training is the practice phase. Inference is the moment you use the trained model to answer a new question.",
    visual: "Training updates the model. Inference uses the model.",
    demo: "training",
    controlLabel: "Training rounds",
    controlMin: 1,
    controlMax: 10,
    controlStep: 1,
    controlDefault: 5,
    quiz: {
      question: "When a chatbot replies to your prompt, which phase are you seeing?",
      options: ["Inference", "Training", "Data labeling"],
      answer: 0,
    },
    takeaway:
      "A trained model can be reused many times without retraining for every request.",
    deeper:
      "Training is expensive because it calculates many updates. Inference is usually cheaper because it only runs the learned parameters forward.",
  },
  {
    id: "loss-optimization",
    number: 3,
    title: "Features, Labels, Loss, and Optimization",
    shortTitle: "Loss",
    theme: "coral",
    summary:
      "Features describe an example, labels are the desired answers, loss measures error, and optimization tries to reduce that error.",
    visual: "The model guesses, loss scores the guess, optimization nudges the model.",
    demo: "loss",
    controlLabel: "Learning rate",
    controlMin: 1,
    controlMax: 100,
    controlStep: 1,
    controlDefault: 38,
    quiz: {
      question: "What does loss tell us?",
      options: [
        "How wrong the model currently is",
        "How many users visited the app",
        "How long the dataset is stored",
      ],
      answer: 0,
    },
    takeaway:
      "Training is a feedback loop: predict, measure error, adjust, repeat.",
    deeper:
      "Gradient descent estimates which direction reduces loss and steps the model's parameters in that direction.",
  },
  {
    id: "neural-networks",
    number: 4,
    title: "Neural Networks in Simple Terms",
    shortTitle: "Networks",
    theme: "blue",
    summary:
      "A neural network stacks small pattern detectors so simple signals can become richer ideas.",
    visual: "Inputs flow through layers. Each layer transforms the signal.",
    demo: "network",
    controlLabel: "Hidden layer width",
    controlMin: 2,
    controlMax: 8,
    controlStep: 1,
    controlDefault: 5,
    quiz: {
      question: "Why do neural networks use layers?",
      options: [
        "To build complex patterns from simpler ones",
        "To avoid using data",
        "To make every answer random",
      ],
      answer: 0,
    },
    takeaway:
      "Layers let a model combine tiny signals into more useful representations.",
    deeper:
      "Modern networks learn intermediate representations that are often hard for humans to name but useful for prediction.",
  },
  {
    id: "llm-difference",
    number: 5,
    title: "What Makes LLMs Different?",
    shortTitle: "LLMs",
    theme: "green",
    summary:
      "Large language models learn from huge text collections and predict useful continuations token by token.",
    visual: "Text becomes tokens, tokens become context, context guides the next token.",
    demo: "llm",
    controlLabel: "Context clues",
    controlMin: 1,
    controlMax: 5,
    controlStep: 1,
    controlDefault: 3,
    quiz: {
      question: "What is an LLM usually trained to predict?",
      options: ["A likely next token", "The weather exactly", "Only yes/no labels"],
      answer: 0,
    },
    takeaway:
      "LLMs are general text pattern engines that can be steered by context.",
    deeper:
      "Instruction tuning and reinforcement learning from feedback make base language models more helpful and conversational.",
  },
  {
    id: "tokens",
    number: 6,
    title: "Tokens and Tokenization",
    shortTitle: "Tokens",
    theme: "violet",
    summary:
      "LLMs do not read text exactly like humans. They split text into chunks called tokens.",
    visual: "A sentence becomes smaller pieces the model can count and process.",
    demo: "tokens",
    controlLabel: "Text sample",
    controlDefault: "LLMs tokenize unfamiliarity, numbers like 2026, and punctuation!",
    quiz: {
      question: "Why do tokens matter?",
      options: [
        "They affect cost, context length, and how the model reads text",
        "They are only used for passwords",
        "They replace all training data",
      ],
      answer: 0,
    },
    takeaway:
      "Tokens are the working units of LLM input and output.",
    deeper:
      "Real tokenizers use learned vocabularies. A token can be a word, part of a word, punctuation, or whitespace pattern.",
  },
  {
    id: "embeddings",
    number: 7,
    title: "Embeddings and Semantic Search",
    shortTitle: "Embeddings",
    theme: "teal",
    summary:
      "Embeddings turn meaning into coordinates, making it possible to search by similarity instead of exact keywords.",
    visual: "Similar ideas land near each other on a map.",
    demo: "embedding",
    controlLabel: "Query idea",
    controlDefault: "How do I learn neural networks?",
    quiz: {
      question: "What should semantic search return?",
      options: [
        "Meaningfully related content",
        "Only identical words",
        "The longest document",
      ],
      answer: 0,
    },
    takeaway:
      "Embeddings help machines compare ideas by meaning.",
    deeper:
      "In production, embeddings usually live in a vector database and are compared with metrics like cosine similarity.",
  },
  {
    id: "attention",
    number: 8,
    title: "Attention and Context Windows",
    shortTitle: "Attention",
    theme: "amber",
    summary:
      "Attention helps an LLM weigh which earlier tokens matter most, while the context window limits what it can see at once.",
    visual: "The model looks back at relevant context before choosing what comes next.",
    demo: "attention",
    controlLabel: "Focus strength",
    controlMin: 1,
    controlMax: 100,
    controlStep: 1,
    controlDefault: 64,
    quiz: {
      question: "What does the context window control?",
      options: [
        "How much text the model can consider at one time",
        "How many colors the website uses",
        "How many GPUs a user owns",
      ],
      answer: 0,
    },
    takeaway:
      "Attention decides what to emphasize; context length decides what is visible.",
    deeper:
      "Transformers compute attention scores between tokens so each token can mix information from relevant positions.",
  },
  {
    id: "prompting",
    number: 9,
    title: "Prompting and Temperature",
    shortTitle: "Prompting",
    theme: "coral",
    summary:
      "Prompts steer the task. Temperature changes how predictable or creative the output feels.",
    visual: "Clear instructions narrow the path. Higher temperature explores more paths.",
    demo: "prompt",
    controlLabel: "Temperature",
    controlMin: 0,
    controlMax: 100,
    controlStep: 1,
    controlDefault: 35,
    quiz: {
      question: "What usually happens when temperature increases?",
      options: [
        "Outputs become more varied",
        "The model stops using tokens",
        "The context window disappears",
      ],
      answer: 0,
    },
    takeaway:
      "Prompt quality shapes direction; temperature shapes variety.",
    deeper:
      "Lower temperature favors high-probability tokens. Higher temperature spreads probability across more possible tokens.",
  },
  {
    id: "rag-agents-evals",
    number: 10,
    title: "RAG, Agents, Fine-tuning, and Evals",
    shortTitle: "Workflows",
    theme: "blue",
    summary:
      "Real LLM apps combine models with retrieval, tools, specialized training, and evaluations.",
    visual: "A useful app is a system around the model, not just the model alone.",
    demo: "workflow",
    controlLabel: "Workflow focus",
    controlDefault: "rag",
    quiz: {
      question: "What does RAG add to an LLM app?",
      options: [
        "Relevant external context before answering",
        "A guarantee that every answer is true",
        "A smaller keyboard",
      ],
      answer: 0,
    },
    takeaway:
      "Strong LLM products use the right workflow for the job and measure quality with evals.",
    deeper:
      "RAG improves access to fresh or private knowledge. Fine-tuning changes behavior. Agents call tools. Evals measure whether the system is working.",
  },
];

export const glossary = [
  ["Agent", "An LLM system that can choose actions, call tools, and continue toward a goal."],
  ["Attention", "A transformer mechanism that weighs which tokens matter most for the next step."],
  ["Context window", "The amount of text a model can consider in one request."],
  ["Embedding", "A numeric representation that places similar meanings near each other."],
  ["Evaluation", "A repeatable way to measure whether a model or LLM app is doing the right thing."],
  ["Feature", "An input signal used by a model, such as age, price, text, or pixels."],
  ["Fine-tuning", "Additional training that adapts a model toward a specific behavior or domain."],
  ["Inference", "Using a trained model to produce a prediction or answer."],
  ["Label", "The target answer used during supervised training."],
  ["Loss", "A score that tells the model how wrong its prediction was."],
  ["Prompt", "The instructions and context sent to an LLM."],
  ["RAG", "Retrieval-augmented generation: find relevant documents, add them to context, then answer."],
  ["Temperature", "A setting that controls how predictable or varied model output is."],
  ["Token", "A chunk of text processed by an LLM."],
  ["Training", "The process of updating a model from examples."],
];

export const useCases = [
  {
    title: "Document Q&A",
    concept: "RAG",
    description: "Search private docs, inject the relevant chunks, and answer with grounded context.",
  },
  {
    title: "Customer Support",
    concept: "Prompting + Evals",
    description: "Guide tone and policy behavior, then test answers against common support cases.",
  },
  {
    title: "Coding Assistant",
    concept: "Context + Tools",
    description: "Use nearby files, error logs, and tool calls to help write, explain, and debug code.",
  },
  {
    title: "Semantic Search",
    concept: "Embeddings",
    description: "Find related ideas even when the exact words do not match.",
  },
  {
    title: "Summarization",
    concept: "Tokens + Context",
    description: "Compress long text while staying inside the model's visible context.",
  },
  {
    title: "Recommendations",
    concept: "ML basics",
    description: "Learn patterns from user behavior and rank the most useful next item.",
  },
];

export const conceptNodes = [
  {
    id: "data",
    label: "Data",
    layer: "ML foundation",
    x: 8,
    y: 22,
    moduleId: "ml-basics",
    description: "Examples give a model something to learn from.",
  },
  {
    id: "features",
    label: "Features + labels",
    layer: "ML foundation",
    x: 23,
    y: 38,
    moduleId: "loss-optimization",
    description: "Features describe examples; labels provide target answers.",
  },
  {
    id: "training",
    label: "Training",
    layer: "ML foundation",
    x: 38,
    y: 22,
    moduleId: "training-inference",
    description: "Training updates model parameters from examples.",
  },
  {
    id: "loss",
    label: "Loss",
    layer: "ML foundation",
    x: 50,
    y: 39,
    moduleId: "loss-optimization",
    description: "Loss measures error and tells optimization what to improve.",
  },
  {
    id: "model",
    label: "Model",
    layer: "ML foundation",
    x: 65,
    y: 24,
    moduleId: "neural-networks",
    description: "The learned model converts inputs into useful predictions.",
  },
  {
    id: "inference",
    label: "Inference",
    layer: "ML foundation",
    x: 84,
    y: 24,
    moduleId: "training-inference",
    description: "Inference uses the trained model without retraining it.",
  },
  {
    id: "prompt",
    label: "Prompt",
    layer: "LLM internals",
    x: 10,
    y: 67,
    moduleId: "prompting",
    description: "Prompts provide the task, constraints, and context.",
  },
  {
    id: "tokens",
    label: "Tokens",
    layer: "LLM internals",
    x: 28,
    y: 67,
    moduleId: "tokens",
    description: "LLMs process text as tokens, not always as whole words.",
  },
  {
    id: "embeddings",
    label: "Embeddings",
    layer: "LLM internals",
    x: 46,
    y: 78,
    moduleId: "embeddings",
    description: "Embeddings turn meaning into searchable coordinates.",
  },
  {
    id: "attention",
    label: "Attention",
    layer: "LLM internals",
    x: 47,
    y: 56,
    moduleId: "attention",
    description: "Attention weighs which earlier tokens matter most.",
  },
  {
    id: "llm",
    label: "LLM",
    layer: "LLM internals",
    x: 65,
    y: 67,
    moduleId: "llm-difference",
    description: "The LLM uses tokens, context, and attention to predict useful continuations.",
  },
  {
    id: "rag",
    label: "RAG",
    layer: "App workflow",
    x: 82,
    y: 51,
    moduleId: "rag-agents-evals",
    description: "RAG retrieves external context before the model answers.",
  },
  {
    id: "agents",
    label: "Agents",
    layer: "App workflow",
    x: 84,
    y: 75,
    moduleId: "rag-agents-evals",
    description: "Agents let an LLM choose tools and continue over multiple steps.",
  },
  {
    id: "fine-tuning",
    label: "Fine-tuning",
    layer: "App workflow",
    x: 62,
    y: 90,
    moduleId: "rag-agents-evals",
    description: "Fine-tuning changes model behavior with additional examples.",
  },
  {
    id: "evals",
    label: "Evals",
    layer: "App workflow",
    x: 92,
    y: 92,
    moduleId: "rag-agents-evals",
    description: "Evals measure whether prompts, RAG, agents, or fine-tuning improved quality.",
  },
];

export const conceptLinks = [
  ["data", "features", "examples become signals"],
  ["features", "training", "used for learning"],
  ["training", "loss", "prediction is scored"],
  ["loss", "training", "feedback updates"],
  ["training", "model", "produces"],
  ["model", "inference", "is used by"],
  ["prompt", "tokens", "text is split"],
  ["tokens", "attention", "context is weighed"],
  ["tokens", "embeddings", "meaning can be mapped"],
  ["attention", "llm", "helps predict"],
  ["prompt", "llm", "steers"],
  ["embeddings", "rag", "powers retrieval"],
  ["rag", "llm", "adds context"],
  ["llm", "agents", "can drive tools"],
  ["llm", "fine-tuning", "can be adapted"],
  ["rag", "evals", "should be measured"],
  ["agents", "evals", "should be measured"],
  ["fine-tuning", "evals", "should be measured"],
];
